version: '3.9'

services:
  # Banco de dados Postgres
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Aplicação Flask
  flask_app:
    build: .
    container_name: flask_app
    env_file:
      - .env
    environment:
      FLASK_APP: manage.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  dbdata:
