version: '3.9'

services:

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dbinit:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

  flask_app:
    build: .
    container_name: flask_app
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_APP=${FLASK_APP}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    depends_on:
      - flask_app
    command: http flask_app:5000
    ports:
      - "4040:4040"  # painel web do ngrok
    restart: unless-stopped

volumes:
  dbinit:
  dbdata:
