version: '3.9'

services:

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dbinit:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

  flask_app:
    build: .
    container_name: flask_app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:${DB_PASS}@postgres:5432/${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  dbinit:
  dbdata:
