version: "3"
services:
  ngrok:
    image: ngrok/ngrok:latest
    env_file:
      - .env
    command:
      - "http"
      - "http://host.docker.internal:8088"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH}
    ports:
      - "4040:4040"
    restart: always